



export const environment = {
  production: true,
  firebaseConfig: {
    apiKey: 'AIzaSyAYu4hMLTk28gkQPNcNEH3nYC6EqC3ZBZM',

    authDomain: 'platart-warehouse-user-mngt.firebaseapp.com',
    databaseURL: 'https://platart-warehouse-user-mngt.firebaseio.com',
    projectId: 'platart-warehouse-user-mngt',
    storageBucket: 'platart-warehouse-user-mngt.appspot.com',
    messagingSenderId: '144533891918',
    appId: '1:144533891918:web:494591651874627f7bcc1f'
  },
  saveCommerce: 'https://platart.com:8081/comerce/savecomerce',
  getAllUsers: 'https://platart.com:8081/user/getallusers',
  getAllMarkers: 'https://platart.com:8081/marker/getallmarkers',
  getAllMarkersNoCoords: 'https://platart.com:8081/marker/getallmarkersNoCoords',
  saveMarker: 'https://platart.com:8081/marker/savemarker',
  saveUser: 'https://platart.com:8081/user/saveuser',
  findUser: 'https://platart.com:8081/user/finduser',
  findCommerce: 'https://platart.com:8081/comerce/find',
  findMarker: 'https://platart.com:8081/marker/find',
  editMarker: 'https://platart.com:8081/marker/edit',
  updateMarker: 'https://platart.com:8081/marker/update',
  deleteMarker: 'https://platart.com:8081/marker/delete',
  deleteCoords: 'https://platart.com:8081/marker/deleteCoords',
  getAllShops: 'https://platart.com:8081/comerce/getallshops',
  getAllActivatedCategories: 'https://platart.com:8081/warehouse/getAllActivatedCategories',
  getAllCategories: 'https://platart.com:8081/warehouse/getAllCategories',
  getAllDeactivatedCategories: 'https://platart.com:8081/warehouse/getAllDeactivatedCategories',
  getAllNewOrderItems: 'https://platart.com:8081/warehouse/getAllNewOrderItems',
  setAllNewOrderItems: 'https://platart.com:8081/warehouse/setAllNewOrderItems',
  verifyAmountItemsOnStock: 'https://platart.com:8081/warehouse/verifyAmountItemsOnStock',
  saveDeliveryOrder: 'https://platart.com:8081/warehouse/sendDeliveryOrder',
  saveListDeliverySupplier: 'https://platart.com:8081/warehouse/savelistdeliverysupplier',
  saveNewCategory: 'https://platart.com:8081/warehouse/saveNewCategory',
  activateCategory: 'https://platart.com:8081/warehouse/activateCategory',
  deactivateCategory: 'https://platart.com:8081/warehouse/deactivateCategory',
  getAllItemsInStock: 'https://platart.com:8081/warehouse/getallitems',
  getDeliveryItemsFromWarehouseByShop: 'https://platart.com:8081/shops/getalldeliveriesnotinstock',
  saveDeliveryItemsToShopStock: 'https://platart.com:8081/shops/saveNewDeliveryFromWarehouse',
  getShopSpecificSoldItemsList: 'https://platart.com:8081/shops/getShopSpecificSoldItemsList',
  saveShopSpecificSoldItemsList: 'https://platart.com:8081/shops/saveShopSpecificSoldItemsList',
  sendSpecificShopSoldItemsList: 'https://platart.com:8081/shops/sendSpecificShopSoldItemsList',
  sendShopSpecificSoldItemsListURL: 'https://platart.com:8081/shops/sendShopSpecificSoldItemsList',
  deleteShopSpecificCheckoutSoldItemsList: 'https://platart.com:8081/shops/deleteShopSpecificCheckoutSoldItemsList',
  loadAllSoldItemsListURL: 'https://platart.com:8081/shops/loadAllCurrentSoldItemsList',
  getTurnoverByDate: 'https://platart.com:8081/dashboard/getTurnoverByDate',
  getTurnoverByShopURL: 'https://platart.com:8081/dashboard/getTurnoverByShop',
  getAggregatedDataForPeriod: 'https://platart.com:8081/dashboard/getAggregatedDataForPeriod',
  getDailyDataForPeriod: 'https://platart.com:8081/dashboard/getDailyDataForPeriod',
  getCategoryDataURL: 'https://platart.com:8081/dashboard/getCategoryData',
  getShopInventoryAvailability: 'https://platart.com:8081/shops/getShopInventoryAvailability',
  getShopInventoryItems: 'https://platart.com:8081/shops/getShopInventoryItems',
  getAllItemsAllShops: 'https://platart.com:8081/shops/getAllItemsAllShops',
  getSoldItemsList: 'https://platart.com:8081/manager/getSoldItemsListByDateRange',
  getCheckinItemsList: 'https://platart.com:8081/manager/getCheckinItemsListByDateRange',
  getAllCheckedInItems: 'https://platart.com:8081/shops/getAllCheckedInItems',
  getSpecificCheckedInItems: 'https://platart.com:8081/shops/getSpecificCheckedInItems',
  getSpecificCheckedInItemsDate: 'https://platart.com:8081/shops/getSpecificCheckedInItemsDate',
  deleteItemsNewDeliveryToShop: 'https://platart.com:8081/warehouse/deleteItems'
};
